name: cd

on:
  push:
    branches: [ master ]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 24 ]

    environment: cd

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v7.0.1

      - name: Setup Vite+ 🏗
        uses: voidzero-dev/setup-vp@v1.21.1
        with:
          node-version: ${{ matrix.node }}
          cache: true

      - name: Check 🔍
        run: vp check

      - name: Generate static website 📸
        run: vp build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true