name: cd

on:
  push:
    branches: [master]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24]

    environment: cd

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Vite+ 🏗
        uses: voidzero-dev/setup-vp@3754dd7dbdb32bd8f6d28b6043de13ad3a75f21f # v1.21.1
        with:
          node-version: ${{ matrix.node }}
          cache: true

      - name: Check 🔍
        run: vp check

      - name: Generate static website 📸
        run: vp build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
